packages:
  - "tools/*"
  - "packages/*"
  - "apps/*"
  - "docs/*"

catalog:
  "@babel/core": ^7.14.5
  "@babel/preset-react": ^7.14.5
  "@eslint/compat": ^1.1.1
  "@eslint/eslintrc": ^2.1.1
  "@faker-js/faker": ^9.6.0
  "@hookform/resolvers": ^4.1.3
  "@ls-lint/ls-lint": ^2.2.3
  "@microsoft/api-extractor": "^7.49.2"
  "@prisma/client": ^6.5.0
  "@prisma/extension-accelerate": ^1.2.2
  "@pump-dot-dump/db": ^0.0.0
  "@radix-ui/react-alert-dialog": ^1.1.6
  "@radix-ui/react-avatar": ^1.1.3
  "@radix-ui/react-checkbox": ^1.1.4
  "@radix-ui/react-dialog": ^1.1.6
  "@radix-ui/react-dropdown-menu": ^2.1.6
  "@radix-ui/react-icons": ^1.3.2
  "@radix-ui/react-label": ^2.1.2
  "@radix-ui/react-navigation-menu": ^1.2.5
  "@radix-ui/react-radio-group": ^1.2.3
  "@radix-ui/react-scroll-area": ^1.2.3
  "@radix-ui/react-select": ^2.1.6
  "@radix-ui/react-separator": ^1.1.2
  "@radix-ui/react-slot": ^1.1.2
  "@radix-ui/react-tabs": ^1.1.3
  "@radix-ui/react-toggle": ^1.1.2
  "@radix-ui/react-toggle-group": ^1.1.2
  "@solana/web3.js": ^1.98.0
  "@stryke/string-format": ^0.2.4
  "@stryke/type-checks": ^0.1.3
  "@stryke/types": latest
  "@swc/cli": ~0.3.12
  "@tailwindcss/postcss": 4.0.12
  "@tanstack/query-broadcast-client-experimental": ^5.69.0
  "@tanstack/query-persist-client-core": ^5.69.0
  "@tanstack/react-form": ^1.1.0
  "@tanstack/react-query": ^5.69.0
  "@tanstack/react-query-devtools": ^5.69.0
  "@tanstack/react-table": ^8.21.2
  "@taplo/cli": ^0.7.0
  "@types/bcryptjs": ^2.4.6
  "@types/jest": "^29.5.14"
  "@types/node": "^22.13.1"
  "@types/react": "^19.0.8"
  "@types/react-dom": "^19.0.3"
  "@nx/next": 20.6.1
  "@nx/devkit": 20.6.1
  "@nx/eslint-plugin": 20.6.1
  "@nx/eslint": 20.6.1
  "@nx/jest": 20.6.1
  "@nx/js": 20.6.1
  "@nx/plugin": 20.6.1
  "@nx/react": 20.6.1
  "@nx/workspace": 20.6.1
  "@storm-software/build-tools": "latest"
  "@storm-software/esbuild": "latest"
  "@storm-software/config": "latest"
  "@storm-software/config-tools": "latest"
  "@storm-software/cspell": "latest"
  "@storm-software/git-tools": "latest"
  "@storm-software/linting-tools": "latest"
  "@storm-software/eslint": "latest"
  "@storm-software/prettier": "latest"
  "@storm-software/unbuild": "latest"
  "@storm-software/untyped": "latest"
  "@storm-software/testing-tools": "latest"
  "@storm-software/tsconfig": "latest"
  "@storm-software/workspace-tools": "latest"
  "@storm-software/markdownlint": "latest"
  "@stryke/http": "latest"
  "@stryke/json": "latest"
  "@swc-node/register": "^1.10.9"
  "@swc/core": "^1.10.14"
  "@swc/wasm": "^1.10.14"
  "@swc/helpers": "^0.5.15"
  autoprefixer: 10.4.13
  better-auth: ^1.2.4
  c12: ^3.0.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dotenv: ^16.4.7
  "eslint": "^9.20.0"
  eslint-config-next: 14.2.16
  eslint-plugin-import: 2.31.0
  eslint-plugin-jsx-a11y: 6.10.1
  eslint-plugin-react: 7.35.0
  eslint-plugin-react-hooks: 5.0.0
  ethers: ^6.13.5
  knip: 5.43.6
  lefthook: ^1.10.10
  ls-lint: ^0.1.2
  lucide-react: ^0.479.0
  markdownlint-cli2: ^0.17.2
  nanostores: ^0.11.4
  next: 15.3.0-canary.12
  next-themes: ^0.4.6
  "nx": 20.6.1
  nx-solhint: ^0.1.4
  postcss: 8.5.3
  postgres: ^3.4.5
  "prettier": "^3.5.3"
  "jest": "^29.7.0"
  "jest-environment-jsdom": "^29.7.0"
  "jest-environment-node": "^29.7.0"
  prettier-plugin-solidity: ^1.4.2
  prettier-plugin-tailwindcss: ^0.6.11
  prisma: ^6.5.0
  prisma-zod-generator: ^0.8.13
  react-csv: ^2.2.2
  react-hook-form: ^7.54.2
  server-only: ^0.0.1
  sharp: 0.33.5
  sherif: 1.3.0
  solhint: ^5.0.5
  solhint-plugin-prettier: ^0.1.0
  sonner: ^2.0.1
  tailwind-merge: ^3.0.2
  tailwindcss: 4.0.14
  tailwindcss-animate: ^1.0.7
  tailwindcss-react-aria-components: 2.0.0
  ts-jest: 29.2.5
  ts-node: 10.9.2
  "tsup": "^8.3.5"
  "tsdown": "^0.5.8"
  "tslib": "^2.8.1"
  "copyfiles": "^2.4.1"
  "rimraf": "^6.0.1"
  "react": "^19.0.0"
  "react-dom": "^19.0.0"
  "react-native": "^0.77.0"
  tsx: ^4.19.3
  tw-animate-css: ^1.2.4
  "typescript": "^5.6.2"
  "esbuild": "^0.24.2"
  "unbuild": "^3.3.1"
  "defu": "^6.1.4"
  "jiti": "^2.4.2"
  verdaccio: 5.33.0
  zod: ^3.24.2
  zod-prisma: ^0.5.4
  zx: ^8.3.2
overrides:
  "@pump-dot-dump/tools-scripts": "workspace:*"
  cookie: ">=0.7.0"
  debug: ">=4.4.0"
  follow-redirects: ">=1.15.9"
  got: ">=14.4.5"
  ip: ">=2.0.1"
  loader-utils: ">=3.3.1"
  markdown-it: ">=14.1.0"
  micromatch: ">=4.0.8"
  next: ">=13.4.20-canary.13"
  node-fetch: ">=3.3.2"
  nth-check: ">=2.1.1"
  parse-path: ">=7.0.0"
  parse-url: ">=9.2.0"
  path-to-regexp: ">=0.1.12"
  postcss: ">=8.5.1"
  shell-quote: ">=1.8.2"
  simple-git: ">=3.27.0"
