packages:
  - "tools/*"
  - "packages/*"
  - "docs/*"

catalog:
  "@microsoft/api-extractor": "^7.52.1"
  "@types/jest": "^29.5.14"
  "@types/node": "^22.13.11"
  "@types/react": "^19.0.8"
  "@types/react-dom": "^19.0.3"
  "@nx/devkit": "^20.6.2"
  "@nx/eslint-plugin": "^20.6.2"
  "@nx/eslint": "^20.6.2"
  "@nx/jest": "^20.6.2"
  "@nx/js": "^20.6.2"
  "@nx/plugin": "^20.6.2"
  "@nx/react": "^20.6.2"
  "@nx/workspace": "^20.6.2"
  "@storm-software/config": "latest"
  "@storm-software/config-tools": "latest"
  "@storm-software/cspell": "latest"
  "@storm-software/git-tools": "latest"
  "@storm-software/linting-tools": "latest"
  "@storm-software/eslint": "latest"
  "@storm-software/prettier": "latest"
  "@storm-software/unbuild": "latest"
  "@storm-software/untyped": "latest"
  "@storm-software/testing-tools": "latest"
  "@storm-software/tsconfig": "latest"
  "@storm-software/workspace-tools": "latest"
  "@storm-software/markdownlint": "latest"
  "@swc-node/register": "^1.10.10"
  "@swc/core": "^1.11.12"
  "@swc/wasm": "^1.11.12"
  "@swc/helpers": "^0.5.15"
  "eslint": "^9.23.0"
  "nx": "^20.6.2"
  "prettier": "^3.5.3"
  "jest": "^29.7.0"
  "jest-environment-jsdom": "^29.7.0"
  "jest-environment-node": "^29.7.0"
  "tsup": "^8.3.5"
  "tsdown": "^0.6.9"
  "tslib": "^2.8.1"
  "copyfiles": "^2.4.1"
  "rimraf": "^6.0.1"
  "react": "^19.0.0"
  "react-dom": "^19.0.0"
  "react-native": "^0.77.0"
  "typescript": "^5.6.2"
  "esbuild": "^0.24.2"
  "unbuild": "^3.5.0"
  "defu": "^6.1.4"
  "jiti": "^2.4.2"
